language: node_js
node_js:
  - 'stable'
cache:
  npm: true
  directories:
    - ~/.cache
script:
  - yarn test:unit
  - yarn test:e2e --headless
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: dist
  on:
    branch: master
