language: node_js
node_js:
  # Node 10.3+ includes npm@6 which has good "npm ci" command
  - 10.8
cache:
  npm: true
  directories:
    - ~/.cache
    - node_modules
install:
  - npm ci
script:
  - yarn test:unit
  - yarn test:e2e
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: dist
  on:
    branch: master
